//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Web_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cdac2022Entities : DbContext
    {
        public cdac2022Entities()
            : base("name=cdac2022Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dept> depts { get; set; }
        public virtual DbSet<desig> desigs { get; set; }
        public virtual DbSet<emp> emps { get; set; }
        public virtual DbSet<grade> grades { get; set; }
        public virtual DbSet<history> histories { get; set; }
        public virtual DbSet<salary> salaries { get; set; }
    }
}
