//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public emp()
        {
            this.emp1 = new HashSet<emp>();
            this.histories = new HashSet<history>();
            this.salaries = new HashSet<salary>();
        }
    
        public string empcode { get; set; }
        public string empname { get; set; }
        public string deptcode { get; set; }
        public System.DateTime birthdate { get; set; }
        public System.DateTime joindate { get; set; }
        public string sex { get; set; }
        public string desigcode { get; set; }
        public string supcode { get; set; }
        public string gradecode { get; set; }
        public string gradelevel { get; set; }
        public Nullable<int> basicpay { get; set; }
    
        public virtual dept dept { get; set; }
        public virtual desig desig { get; set; }
        public virtual grade grade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emp> emp1 { get; set; }
        public virtual emp emp2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<history> histories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salary> salaries { get; set; }
    }
}
