//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public string empcode { get; set; }
        public System.DateTime changedate { get; set; }
        public string desigcode { get; set; }
        public string gradecode { get; set; }
        public string gradelevel { get; set; }
        public Nullable<int> basicpay { get; set; }
    
        public virtual desig desig { get; set; }
        public virtual emp emp { get; set; }
        public virtual grade grade { get; set; }
    }
}
