//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salary
    {
        public string empcode { get; set; }
        public System.DateTime salmonth { get; set; }
        public Nullable<int> basic { get; set; }
        public Nullable<int> allow { get; set; }
        public Nullable<int> deduct { get; set; }
    
        public virtual emp emp { get; set; }
    }
}
