// <auto-generated />
namespace CategoryProduct.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addCoumnINCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCoumnINCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "202301310726322_addCoumnINCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
